name: glimmer
description: "Discover your dream bridal jewelry with our elegant app, showcasing a stunning catalogue of pieces in a clean, image-focused design."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
